version: "3.3"
services:
  dbserver:
    image: mysql:5.7
    ports:
      - "5506:3306"
    command: >
      mysqld
        --character-set-server=utf8
        --collation-server=utf8_unicode_ci
        --skip-character-set-client-handshake
    hostname: dbserver
    environment:
      MYSQL_DATABASE: sample
      MYSQL_USER: master
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password